project:
  type: website
  output-dir: _site
  render: 
    - index.qmd
    - research.qmd
    - teaching.qmd
    - cv.qmd

website:
  title: "Michael D. Siciliano"
  navbar:
    left:
      - href: index.qmd
        text: About
      - research.qmd
      - teaching.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

